name: "💡 Feature Request / 機能リクエスト"
description: "Suggest a new feature idea / 新機能のアイデアを提案する"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for your suggestion!**  
        機能の提案ありがとうございます。以下の情報を記入してください。

  - type: textarea
    id: problem
    attributes:
      label: Related Issue / 関連する問題
      description: |
        Describe any related issues this request addresses.  
        この機能リクエストに関連する問題を説明してください
      placeholder: |
        e.g.) It’s cumbersome to do “…”  
        例）〜の操作が面倒です
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution / 提案する解決策
      description: |
        Explain your suggested solution.  
        考えられる解決策を説明してください
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered / 代替案
      description: |
        List other options you considered.  
        検討した他の解決策があれば記述してください
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context / その他の情報
      description: |
        Attach screenshots, mockups, or links if available.  
        スクリーンショットや参考資料などがあれば追加してください
    validations:
      required: false
